
/* printing a PFA representation of a PST */
/* this is a GENERAL USE version */

#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include "file_handle.h"
#include "pfa.h"


int main (int argc, char **argv)
{


  int absize;
  int max_L;
  int nodes = 0, added_nodes = 0;
  char *AB, *pst_file, *pfa_file;
  pst_type T;
  pfa_type M;

  switch (argc)
    {
    case 1:  /* short reminder */
      system("clear");
      printf(" (clear screen)\n");
      fprintf(stderr,"GENERAL call format:\n\nGenerating a PFA representation of a given PST:\n\n");
      fprintf(stderr," %s <pst_file> <pfa_file>\n\n\n",argv[0]);
      fprintf(stderr,"<pst_file>    a PST generated by train\n");
      fprintf(stderr,"<pfa_file>    an equivalent PFA\n\n");
      exit(1);

    case 3:
      pst_file = argv[1];
      pfa_file = argv[2];
      break;
      
    default:
      fprintf(stderr,"Syntax Error: type %s for a short reminder\n",argv[0]);
      exit(1);

    }
  

  /* pst2pfa */

  load_pst (pst_file, &AB, &absize, &max_L, &T);

  extend_pst(AB, absize, max_L, T, &nodes, &added_nodes);
  /* max_L is conserved in extension */

  printf("PST   nodes: %d\n", nodes);
  printf("dummy nodes: %d  (%2.0f%%)\n", added_nodes, 100.0*added_nodes/nodes);
  printf("PFA   nodes: %d\n", nodes + added_nodes);

  /* print_pfa_form(AB, absize, max_L, T, stderr, stderr); */

  M = make_empty_pfa(absize, nodes+added_nodes);

  epst2pfa(AB, absize, max_L, T, M);
  if (M.node[M.nodes-1].label == NULL)
    {
      fprintf(stderr,"c-code bug: the PFA should be full\n");
      exit(1);
    }

  solve_stat_pfa(M, absize);

  save_pfa(pfa_file, AB, absize, max_L, M);

  return(0);
  
}    

